# Programmers SQL L3: 없어진 기록 찾기
# Date : 2021.01.31
# JOIN

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_INS AI, ANIMAL_OUTS AO
WHERE AI.ANIMAL_ID(+) = AO.ANIMAL_ID AND
      AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID;
