# Programmers SQL L4: 보호소에서 중성화한 동물
# Date : 2021.01.31
# JOIN

SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM   ANIMAL_INS AI ,ANIMAL_OUTS AO
WHERE  AI.ANIMAL_ID = AO.ANIMAL_ID
       AND    AI.ANIMAL_TYPE = AO.ANIMAL_TYPE
       AND    AI.SEX_UPON_INTAKE LIKE 'Intact%'
       AND  (AO.SEX_UPON_OUTCOME LIKE 'Neutered%' OR AO.SEX_UPON_OUTCOME LIKE 'Spayed%')
