# Programmers SQL L3: 있었는데요 없었습니다
# Date : 2021.01.31
# JOIN

SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AI, ANIMAL_OUTS AO
WHERE AI.ANIMAL_ID = AO.ANIMAL_ID AND
      AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME
