# Programmers SQL L2: 입양 시각 구하기1
# Date : 2021.01.26
# GROUP BY

SELECT HOUR, COUNT(HOUR) AS COUNT
FROM (SELECT TO_CHAR(DATETIME,'HH24')HOUR
      FROM ANIMAL_OUTS)
WHERE HOUR >=9 AND HOUR <= 19
GROUP BY HOUR
ORDER BY HOUR

# HH, HH12, HH24(시간표기 12시간, 24시간표기)
